version: '3.8'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: edunexususer
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: edunexus
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: ./project_backend_django  # Path to your Django Dockerfile
    volumes:
      - ./project_backend_django:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build: ./project_front_react # Path to your React Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:

